version: "3"
services:
  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: yarn react-scripts start